(()=>{'use strict';const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const TONES={hero:['#3a2f2a','#8c6f55'],rose:['#f0dcd4','#d9b8ae'],gold:['#efdfc0','#c3a06b'],nude:['#f2e5d6','#d8bfa5'],mauve:['#e8d6da','#b99aa3'],cream:['#f9f2e7','#e6d6bd']};
function ph(t,w,h){const[c1,c2]=TONES[t]||TONES.cream;const s=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><defs><linearGradient id="g"><stop stop-color="${c1}"/><stop offset="1" stop-color="${c2}"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/></svg>`;return'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(s)}
$$('img[data-tone]').forEach(img=>{const fallback=()=>{if(img.dataset.phApplied)return;img.dataset.phApplied=1;img.src=ph(img.dataset.tone,+img.width||800,+img.height||600)};if(img.complete&&img.naturalWidth===0)fallback();else img.addEventListener('error',fallback,{once:true})});
const header=$('#header');if(header){const f=()=>header.classList.toggle('is-scrolled',scrollY>40);f();addEventListener('scroll',f,{passive:true})}
const burger=$('#burger'),nav=$('#nav');if(burger&&nav){const set=o=>{nav.classList.toggle('is-open',o);document.body.classList.toggle('no-scroll',o);burger.setAttribute('aria-expanded',String(o));burger.setAttribute('aria-label',o?'Закрити меню':'Відкрити меню')};burger.onclick=()=>set(!nav.classList.contains('is-open'));$$('a',nav).forEach(a=>a.onclick=()=>set(false));addEventListener('resize',()=>{if(innerWidth>900)set(false)})}
const links=$$('.nav__link'),sections=links.map(a=>$(a.getAttribute('href'))).filter(Boolean);if('IntersectionObserver'in window){const spy=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('is-active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-45% 0px -50% 0px'});sections.forEach(s=>spy.observe(s))}
const reveals=$$('.reveal');reveals.forEach(e=>e.style.setProperty('--rd',(parseInt(e.dataset.delay)||0)+'ms'));if('IntersectionObserver'in window){const io=new IntersectionObserver((es,o)=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');o.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -6% 0px'});reveals.forEach(e=>io.observe(e))}else reveals.forEach(e=>e.classList.add('is-visible'));
const y=$('#year');if(y)y.textContent=new Date().getFullYear();$$('[data-placeholder]').forEach(a=>a.onclick=e=>e.preventDefault());$$('[data-book-service]').forEach(a=>a.onclick=()=>{const s=$('#bk-service');if(s&&[...s.options].some(o=>o.value===a.dataset.bookService)){s.value=a.dataset.bookService;s.dispatchEvent(new Event('change',{bubbles:true}))}});
})();